/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.USUARIO DROP CONSTRAINT PERFIL_FK;
ALTER TABLE LABDATABASE.AGENDA DROP CONSTRAINT USUARIO_FK;

/*Apaga as tabelas*/
DROP TABLE LABDATABASE.PERFILS;
DROP TABLE LABDATABASE.USUARIO;
DROP TABLE LABDATABASE.AGENDA;

/*Apaga as sequences*/
DROP SEQUENCE LABDATABASE.PERFILS_CODIGO_SEQ;
DROP SEQUENCE LABDATABASE.USUARIO_CODIGO_SEQ;
DROP SEQUENCE LABDATABASE.AGENDA_CODIGO_SEQ;

/*Cria as tabelas*/

CREATE TABLE LABDATABASE.USUARIO (
                CODIGO_USUARIO NUMBER NOT NULL,  
                NOME VARCHAR2(255) NOT NULL,
                EMAIL VARCHAR2(255) NOT NULL,
                IDADE_USUARIO NUMBER(9,2) NOT NULL,
                ALTURA_USUARIO NUMBER(9,3) NOT NULL,
                PESO_USUARIO NUMBER(9,2) NOT NULL,
                CODIGO_PERFIL NUMBER NOT NULL,
                CONSTRAINT CODIGO_USUARIO_PK PRIMARY KEY (CODIGO_USUARIO)
);

CREATE TABLE LABDATABASE.PERFILS (
                CODIGO_PERFIL NUMBER NOT NULL,
                DESCRICAO_PERFIL VARCHAR2(255) NOT NULL,
                PORCENTAGEM_PERFIL NUMBER(9,2) NOT NULL,
                CONSTRAINT PERFIL_PK PRIMARY KEY (CODIGO_PERFIL)
);

CREATE TABLE LABDATABASE.AGENDA (
                CODIGO_AGENDA NUMBER NOT NULL,  
                QTD_INDICADA NUMBER(9,3) NOT NULL,
                QTD_CONSUMIDA NUMBER(9,3) NOT NULL,
                QTD_TOTAL NUMBER(9,3) NOT NULL,
                DATA_CADASTRO DATE NOT NULL,
                CODIGO_USUARIO NUMBER NOT NULL,
                CONSTRAINT CODIGO_AGENDA_PK PRIMARY KEY (CODIGO_AGENDA )
);

/*Cria as sequences*/
CREATE SEQUENCE LABDATABASE.PERFILS_CODIGO_SEQ;
CREATE SEQUENCE LABDATABASE.USUARIO_CODIGO_SEQ;
CREATE SEQUENCE LABDATABASE.AGENDA_CODIGO_SEQ;


/*Cria os relacionamentos*/

ALTER TABLE LABDATABASE.USUARIO ADD CONSTRAINT PERFIL_FK
FOREIGN KEY (CODIGO_PERFIL)
REFERENCES LABDATABASE.PERFILS (CODIGO_PERFIL)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.AGENDA ADD CONSTRAINT USUARIO_FK
FOREIGN KEY (CODIGO_USUARIO)
REFERENCES LABDATABASE.USUARIO (CODIGO_USUARIO)
NOT DEFERRABLE;


/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.PERFILS TO LABDATABASE;
GRANT ALL ON LABDATABASE.USUARIO TO LABDATABASE;
GRANT ALL ON LABDATABASE.AGENDA TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;